name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        # You can remove libayatana-appindicator3-dev if you don't use the system tray feature.
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: |
          npm install -g pnpm
          pnpm install

      - name: Print Secret
        run: |
          echo "Secret Value: ${{ secrets.TAURI_PRIVATE_KEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5Ry9SVGxpeTZrZGxScGZ1dFh3cmtJNzFEUFJMdHo3LzBDZjU4WUJJalllSUFBQkFBQUFBQUFBQUFBQUlBQUFBQW5pQmJQT3ZtYTc4WFNxa3lyaHpLQnpObm9rNkRlckNDdXcxcDE3RzFzZGh3SnFGRUZHVDNSL1FBSGRxTDRNMGZvODBac1dlVHdjalY5cTNyaG5vMEgyL1ZKVmJ0ZFRrUW96Y3VDVi90cjBzNkt5VmxUaktiRkNNQ3NsSkh4MG5HbEZvaEdwVWZsZHc9Cg==
          TAURI_KEY_PASSWORD: 9a287a9e588436966952d62ba1e121e2

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IHJzaWduIGVuY3J5cHRlZCBzZWNyZXQga2V5ClJXUlRZMEl5Ry9SVGxpeTZrZGxScGZ1dFh3cmtJNzFEUFJMdHo3LzBDZjU4WUJJalllSUFBQkFBQUFBQUFBQUFBQUlBQUFBQW5pQmJQT3ZtYTc4WFNxa3lyaHpLQnpObm9rNkRlckNDdXcxcDE3RzFzZGh3SnFGRUZHVDNSL1FBSGRxTDRNMGZvODBac1dlVHdjalY5cTNyaG5vMEgyL1ZKVmJ0ZFRrUW96Y3VDVi90cjBzNkt5VmxUaktiRkNNQ3NsSkh4MG5HbEZvaEdwVWZsZHc9Cg==
          TAURI_KEY_PASSWORD: 9a287a9e588436966952d62ba1e121e2
        with:
          tagName: ${{ github.ref_name }} # This only works if your workflow triggers on new tags.
          releaseName: "App Name v__VERSION__" # tauri-action replaces \_\_VERSION\_\_ with the app version.
          releaseBody: "See the assets to download and install this version."
          releaseDraft: true
          prerelease: false
